/**
 * Precomputes the light for every item shape and writes ../shade.gen.ts (DESIGN §10.4: crescents
 * are precomputed, never clipped at run time).
 *
 * For each shape registered with `shapes()` it stores:
 * - `c`: the shade crescents for light from the left, top and right: the shape minus itself nudged
 *   toward the light by CRESCENT_OFFSET × k, which leaves a hard-edged sliver on the far side;
 * - `r`: for dark shapes, the lamp-side rim light: the shape minus itself nudged away from the light;
 * - `d`: for patches with a `clip`, the patch trimmed to that shape (stripes on a canopy).
 *
 * Run it after changing any shape. It needs paper.js for Bézier boolean operations, installed
 * anywhere outside the repo (nothing here ships):
 *   npm i --prefix /tmp/paper paper@0.12
 *   PAPER_DIR=/tmp/paper npx vite-node src/art/scene/decor/tools/build-shade.mjs
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const require = createRequire(process.env.PAPER_DIR ? `${process.env.PAPER_DIR}/node_modules/` : import.meta.url);
const paper = require('paper');
paper.setup(new paper.Size(100, 100));

// Importing the art registers every shape.
await import('../index.ts');
await import('../../../items/index.tsx');
const { SHAPES, CRESCENT_OFFSET, RIM_WIDTH, LIGHT_ORDER, shapeHash } = await import('../kit.tsx');

/** Slivers smaller than this (canvas units²) are rounding dust, not shade. */
const SPECK = 0.35;

const create = (d) => paper.PathItem.create(d);

/** Compact path data at 0.1 precision, without specks. */
function data(item) {
  if (!item || item.isEmpty()) return '';
  const parts = item.children ? [...item.children] : [item];
  for (const part of parts) if (Math.abs(part.area) < SPECK) part.remove();
  if (item.isEmpty() || Math.abs(item.area) < SPECK) return '';
  return item
    .getPathData(null, 1)
    .replace(/,/g, ' ')
    .replace(/ -/g, '-')
    .replace(/([a-zA-Z]) /g, '$1')
    .replace(/(?<![\d])0\./g, '.');
}

function minusShifted(base, dx, dy) {
  const moved = base.clone({ insert: false });
  moved.translate(new paper.Point(dx, dy));
  return data(base.subtract(moved, { insert: false }));
}

const rows = [];
for (const shape of [...SHAPES.values()].sort((a, b) => a.ref.localeCompare(b.ref))) {
  let base = create(shape.d);
  const row = { h: shapeHash(shape) };
  if (shape.clip) {
    const target = SHAPES.get(shape.clip);
    if (!target) throw new Error(`${shape.ref}: clip target ${shape.clip} is not registered`);
    base = base.intersect(create(target.d), { insert: false });
    row.d = data(base.clone({ insert: false }));
  }
  if (shape.k > 0) {
    row.c = LIGHT_ORDER.map((from) => {
      const [x, y] = CRESCENT_OFFSET[from];
      return minusShifted(base, x * shape.k, y * shape.k);
    });
  }
  if (shape.rim) {
    row.r = LIGHT_ORDER.map((from) => {
      const [x, y] = CRESCENT_OFFSET[from];
      const len = Math.hypot(x, y);
      return minusShifted(base, (-x / len) * RIM_WIDTH, (-y / len) * RIM_WIDTH);
    });
  }
  rows.push([shape.ref, row]);
}

const body = rows.map(([ref, row]) => `  ${JSON.stringify(ref)}: ${JSON.stringify(row)},`).join('\n');
const out = `/* Generated by src/art/scene/decor/tools/build-shade.mjs. Do not edit by hand. */

/** One shape's precomputed light: its trimmed path, crescents and rims for light from the left, top and right. */
export interface ShadeRow {
  /** Fingerprint of the shape this row was computed from (see \`shapeHash\`). */
  h: string;
  /** The shape trimmed to its clip shape, when it has one. */
  d?: string;
  /** Shade crescents: [left, top, right]. */
  c?: readonly [string, string, string];
  /** Lamp-side rim lights for dark shapes: [left, top, right]. */
  r?: readonly [string, string, string];
}

export const SHADE: Readonly<Record<string, ShadeRow>> = {
${body}
};
`;
const target = fileURLToPath(new URL('../shade.gen.ts', import.meta.url));
writeFileSync(target, out);
console.log(`shade.gen.ts: ${rows.length} shapes, ${(out.length / 1024).toFixed(1)} KB`);
