/**
 * Writes the precomputed light as two generated files (shared by build-shade.mjs):
 * - ../shade.gen.ts: the rows the art reads, only for shapes that have light to draw (a crescent,
 *   a rim or a trim), as one JSON.parse string (parsed faster than an object literal);
 * - ../shade.hash.gen.ts: every shape's fingerprint, read only by decor.test.ts's staleness check,
 *   so the hashes never ship.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const HEAD = '/* Generated by src/art/scene/decor/tools/build-shade.mjs. Do not edit by hand. */\n';

/** `rows`: [ref, { h, d?, c?, r? }] sorted by ref. Returns the two files' sizes in bytes. */
export function emitShade(rows) {
  const table = {};
  const hashes = {};
  for (const [ref, { h, ...light }] of rows) {
    hashes[ref] = h;
    if (Object.keys(light).length) table[ref] = light;
  }
  const shade = `${HEAD}
/** One shape's precomputed light: its trimmed path, crescents and rims for light from the left, top and right. */
export interface ShadeRow {
  /** The shape trimmed to its clip shape, when it has one. */
  d?: string;
  /** Shade crescents: [left, top, right]. */
  c?: readonly [string, string, string];
  /** Lamp-side rim lights for dark shapes: [left, top, right]. */
  r?: readonly [string, string, string];
}

/** Rows for shapes with light to draw; a shape with none (no crescent, rim or trim) has no row. */
export const SHADE: Readonly<Record<string, ShadeRow>> = JSON.parse('${JSON.stringify(table).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}');
`;
  const hash = `${HEAD}
/** Every registered shape's fingerprint when its row was computed (see \`shapeHash\`); for decor.test.ts only. */
export const SHADE_HASH: Readonly<Record<string, string>> = ${JSON.stringify(hashes, null, 0).replace(/","/g, '",\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, ',\n}')};
`;
  writeFileSync(fileURLToPath(new URL('../shade.gen.ts', import.meta.url)), shade);
  writeFileSync(fileURLToPath(new URL('../shade.hash.gen.ts', import.meta.url)), hash);
  return { shade: shade.length, hash: hash.length };
}
