/**
 * The demo (DESIGN §9.5 "Demo", §11.1 "Just peek"): ~120 days of realistic history
 * generated by driving the *real* reducers day by day with a seeded rng, so every number on every
 * screen is internally consistent (the wallet matches the ledger, plants match their sunshine,
 * badges and letters were earned the normal way, and `validateState` passes).
 *
 * The story: seven habits covering every schedule kind (daily count habit with a tiny version,
 * daily, certain days, weekly, monthly, an "avoid" habit, all four time blocks); a sick week with
 * off days; a vacation pause; a habit started mid-way; a schedule edit; notes on some days; the
 * "Cats or Cows?" capsule at onboarding, then capsule pulls (≈ 14 pets), treats, outfits and
 * favourites; decor placed; the Saucer Pond opened; and last week's Sunday Note still waiting on
 * the sill. Keeping Company: the first friend lives in the reading plant, later friends sometimes
 * choose a plant, their keepsakes sit on the sill; the walk follows the vitamins; some notes are
 * starred for the Sunday Note.
 */
import { MACHINES } from '@/catalog/machines';
import { COLLECTIBLES, getCollectible } from '@/catalog/collectibles';
import type { MachineId } from '@/catalog/types';
import type { HabitInput } from './api';
import type { AppState, DateKey, StoryId } from './types';
import { createInitialState } from './defaults';
import { addDays, appDayKey, monotonicDayKey, parseDateKey, runtimeLocalTime, weekday, type LocalTimeReader } from '@/domain/dates';
import { chance, mulberry32, pick, randomInt, type Rng } from '@/domain/rng';
import { transact, type Env, type Tx } from '@/domain/tx';
import { openDay } from '@/domain/rollover';
import * as habits from '@/domain/habits';
import * as logging from '@/domain/logging';
import * as gacha from '@/domain/gacha';
import * as friendship from '@/domain/friendship';
import * as shelf from '@/domain/shelf';
import * as pantry from '@/domain/pantry';
import { readLetter } from '@/domain/letters';
import * as company from '@/domain/company';
import { availableMachineIds } from '@/domain/seasons';
import { ownedTreats, ownedWearables } from '@/domain/collection';
import { isScheduledOn } from '@/domain/rules';

export interface DemoOptions {
  /** The app day the demo should end on (normally the real today). */
  today: DateKey;
  /** The real current time; nothing in the demo happens after it. */
  now: number;
  local?: LocalTimeReader;
  seed?: number;
  days?: number;
  name?: string;
}

/** Epoch ms at which `local` shows `hour:minute` on `date` (DST-safe to within the gap hour). */
export function epochAtLocal(date: DateKey, hour: number, minute: number, local: LocalTimeReader): number {
  const { year, month, day } = parseDateKey(date);
  const target = Date.UTC(year, month - 1, day, hour, minute);
  let guess = target;
  for (let i = 0; i < 3; i++) {
    const t = local(guess);
    const shown = Date.UTC(t.year, t.month - 1, t.day, t.hour, t.minute);
    if (shown === target) return guess;
    guess += target - shown;
  }
  return guess;
}

const NOTES = [
  'Felt so much better after this.',
  'Tiny version, but I showed up.',
  'Rainy, but did it anyway.',
  'Listened to a podcast the whole time.',
  'New personal best.',
  'Tired today. Still counts.',
  'Did it with a friend.',
  'Sunset was unreal tonight.',
];

type BlockHour = Record<HabitInput['timeOfDay'], [number, number]>;
const BLOCK_TIME: BlockHour = { morning: [7, 40], midday: [12, 30], evening: [20, 15], anytime: [17, 10] };

class Sim {
  state: AppState;
  now: number;
  readonly rng: Rng;
  constructor(
    readonly local: LocalTimeReader,
    seed: number,
    start: number,
  ) {
    this.rng = mulberry32(seed);
    this.now = start;
    this.state = createInitialState(start);
  }
  get today(): DateKey {
    return monotonicDayKey(appDayKey(this.now, this.state.settings.dayStartsAt, this.local), this.state.clock.maxDateKey);
  }
  env(): Env {
    return { now: this.now, today: this.today, local: this.local, rng: this.rng };
  }
  run<R>(body: (tx: Tx) => R): R {
    const out = transact(this.state, this.env(), (tx) => {
      openDay(tx);
      return { r: body(tx) };
    });
    this.state = out.state;
    return out.r;
  }
}

/** Builds the demo ending on `opts.today` (deterministic for a given seed and today). */
export function buildDemo(opts: DemoOptions): AppState {
  const local = opts.local ?? runtimeLocalTime;
  const days = opts.days ?? 120;
  const start = addDays(opts.today, -(days - 1));
  const sim = new Sim(local, opts.seed ?? 20260929, epochAtLocal(start, 8, 5, local));
  const rng = sim.rng;
  const at = (date: DateKey, h: number, m: number) => epochAtLocal(date, h, m, local);

  sim.run((tx) => habits.completeOnboarding(tx, { name: opts.name ?? 'Sam', templateIds: [] }));
  // "Cats or Cows?": the first pet comes home with onboarding's free capsule.
  sim.run((tx) => {
    gacha.pull(tx, 'cats', { free: true });
    gacha.finishReveal(tx);
  });

  const make = (input: Partial<HabitInput> & Pick<HabitInput, 'name' | 'icon'>): string =>
    sim.run((tx) =>
      habits.createHabit(tx, {
        color: 'sage',
        plant: 'pothos',
        pot: 'terracotta',
        schedule: { kind: 'daily' },
        target: 1,
        step: 1,
        effort: 'steady',
        timeOfDay: 'anytime',
        polarity: 'build',
        ...input,
      }),
    );

  const ids = {
    water: make({ name: 'Drink water', icon: 'water', color: 'sky', plant: 'pothos', target: 8, unit: 'glasses', effort: 'light', tiny: { label: '4 glasses', count: 4 } }),
    vitamins: make({ name: 'Take vitamins', icon: 'vitamins', color: 'butter', plant: 'catgrass', pot: 'cream', effort: 'light', timeOfDay: 'morning', anchor: 'After I pour my coffee' }),
    walk: make({ name: 'Go for a walk', icon: 'walk', color: 'sage', plant: 'snakeplant', timeOfDay: 'midday', tiny: { label: 'Shoes on, step outside' } }),
    read: make({ name: 'Read', icon: 'book', color: 'mint', plant: 'begonia', pot: 'blush', schedule: { kind: 'days', days: [1, 3, 5] }, timeOfDay: 'evening', tiny: { label: 'One page' } }),
    yoga: make({ name: 'Yoga', icon: 'yoga', color: 'lavender', plant: 'pilea', schedule: { kind: 'weekly', times: 2, every: 1 }, timeOfDay: 'evening', tiny: { label: 'One sun salutation' } }),
    clean: make({ name: 'Deep clean', icon: 'sparkle-clean', color: 'peach', plant: 'snakeplant', schedule: { kind: 'monthly', times: 1, every: 1 }, effort: 'big' }),
  };
  let phoneFree: string | null = null;
  const yogaDays = new Set<number>([2, 4]);
  // Keeping Company (§14.1): the first friend moves into the reading plant ("Find them a plant"),
  // the walk follows the vitamins (§14.2 stacking), and reading has a why.
  sim.run((tx) => {
    const first = Object.keys(tx.s.pets)[0];
    if (first) company.setCompanion(tx, ids.read, first);
    habits.updateHabit(tx, ids.walk, { anchorHabitId: ids.vitamins, why: 'Fresh air before the afternoon.' });
  });

  const sickStart = 36;
  const vacationStart = 76;
  for (let i = 0; i < days; i++) {
    const date = addDays(start, i);
    const last = i === days - 1;
    const sick = i >= sickStart && i < sickStart + 7;
    const vacation = i >= vacationStart && i < vacationStart + 9;
    const recovering = i >= sickStart + 7 && i < sickStart + 14;
    const p = sick ? 0.3 : vacation ? 0.55 : recovering ? 0.75 : i < 20 ? 0.8 : 0.88;

    const moment = (h: number, m: number): boolean => {
      const t = at(date, h, m + randomInt(rng, 0, 25));
      if (t > opts.now) return false;
      sim.now = t;
      return true;
    };

    if (!moment(7, 5)) break;
    sim.run(() => undefined);
    if (i === sickStart + 2 || i === sickStart + 3 || i === sickStart + 4) sim.run((tx) => logging.toggleOffDay(tx, date));
    if (i === vacationStart - 2) {
      sim.run((tx) => {
        habits.pauseHabit(tx, ids.walk, addDays(date, 2), addDays(date, 10));
        habits.pauseHabit(tx, ids.read, addDays(date, 2), addDays(date, 10));
      });
    }
    if (i === 50) {
      phoneFree = make({ name: 'Phone-free bedtime', icon: 'no-phone', color: 'lilac', plant: 'catgrass', timeOfDay: 'evening', polarity: 'avoid', anchor: 'Phone charges in the kitchen' });
    }
    if (i === 58) sim.run((tx) => habits.updateHabit(tx, ids.walk, { schedule: { kind: 'days', days: [1, 2, 3, 4, 5, 6] } }));

    const order: [keyof typeof ids | 'phone', HabitInput['timeOfDay']][] = [
      ['vitamins', 'morning'],
      ['walk', 'midday'],
      ['water', 'anytime'],
      ['clean', 'anytime'],
      ['yoga', 'evening'],
      ['read', 'evening'],
      ['phone', 'evening'],
    ];
    for (const [key, block] of order) {
      const id = key === 'phone' ? phoneFree : ids[key];
      if (!id) continue;
      const [h, m] = BLOCK_TIME[block];
      if (!moment(h, m)) break;
      const habit = sim.state.habits.find((x) => x.id === id)!;
      if (habit.pauses.some((ps) => ps.start <= date && (!ps.end || date <= ps.end))) continue;
      if (key === 'yoga') {
        if (!yogaDays.has(weekday(date)) && !chance(rng, 0.08)) continue;
        if (!chance(rng, p + 0.05)) continue;
      } else if (key === 'clean') {
        const dom = parseDateKey(date).day;
        if (dom < 8 || dom > 24 || !chance(rng, 0.12)) continue;
        const month = date.slice(0, 7);
        if (Object.keys(sim.state.logs[id] ?? {}).some((d) => d.startsWith(month))) continue;
      } else if (!isScheduledOn(habit, date) || !chance(rng, p)) {
        if (key === 'walk' && isScheduledOn(habit, date) && chance(rng, 0.2)) sim.run((tx) => logging.toggleRest(tx, id, date));
        continue;
      }
      if (key === 'water') {
        const glasses = sick ? randomInt(rng, 3, 6) : randomInt(rng, 5, 9);
        for (let g = 0; g < glasses; g++) {
          sim.now += randomInt(rng, 20, 50) * 60_000;
          if (sim.now > opts.now) break;
          sim.run((tx) => logging.checkIn(tx, id));
        }
        continue;
      }
      const tinyDay = (sick || chance(rng, 0.08)) && habit.rules.at(-1)!.tiny !== undefined;
      sim.run((tx) => (tinyDay ? logging.checkInTiny(tx, id) : logging.checkIn(tx, id)));
      if (chance(rng, 0.07)) {
        sim.run((tx) => {
          logging.setNote(tx, id, date, pick(rng, NOTES));
          if (chance(rng, 0.5)) logging.starNote(tx, id, date, true);
        });
      }
    }

    // Forgot to log last night's reading; backfilled with breakfast.
    if (i % 17 === 5 && !last) {
      const y = addDays(date, -1);
      const readHabit = sim.state.habits.find((x) => x.id === ids.read)!;
      if (isScheduledOn(readHabit, y) && !sim.state.logs[ids.read]?.[y] && moment(8, 30)) sim.run((tx) => logging.checkIn(tx, ids.read, y));
    }

    if (!moment(21, 30)) continue;
    eveningOnTheShelf(sim, date, rng);
  }

  // Rituals: everything read except the latest Sunday Note (it waits on the sill). Stories: all
  // opened except the newest (it waits on its plant tag); reading's "Why it matters" was answered.
  sim.run((tx) => {
    const weekly = tx.s.inbox.filter((l) => l.kind === 'weekly');
    const keep = weekly[weekly.length - 1]?.id;
    for (const l of tx.s.inbox) if (l.id !== keep) readLetter(tx, l.id);
    const stories = Object.values(tx.s.company?.pairs ?? {})
      .flatMap((p) => Object.entries(p.stories ?? {}).map(([story, st]) => ({ habitId: p.habitId, story: story as StoryId, on: st!.on })))
      .sort((a, b) => (a.on < b.on ? -1 : a.on > b.on ? 1 : 0));
    for (const st of stories.slice(0, -1)) company.readStory(tx, st.habitId, st.story);
    for (const p of Object.values(tx.s.company?.pairs ?? {})) {
      if (p.stories?.why && tx.s.habits.find((h) => h.id === p.habitId)?.companionId === p.petId) company.answerWhy(tx, p.habitId, p.habitId === ids.read ? 'Evenings feel longer with a book.' : null);
    }
  });
  return sim.state;
}

/** An evening on the Shelf: capsules, pets, treats, outfits, decor and a place. */
function eveningOnTheShelf(sim: Sim, date: DateKey, rng: Rng): void {
  const s = () => sim.state;
  // Capsules: about one pull every few evenings until ~14 pets live here, then the odd pull.
  const friends = Object.keys(s().pets).length;
  const wantsPull = friends < 14 ? chance(rng, 0.3) : chance(rng, 0.1);
  if (s().wallet.coins >= 90 && wantsPull) {
    const coinMachines = availableMachineIds(date).filter((m) => MACHINES.find((x) => x.id === m)!.currency === 'coins') as MachineId[];
    const machine = pick(rng, coinMachines);
    sim.run((tx) => {
      const out = gacha.pull(tx, machine);
      gacha.finishReveal(tx);
      // A new friend is offered a plant; now and then she lets them choose.
      if (out.ok && out.pet && chance(rng, 0.5) && company.companionOfferOpen(tx.s, tx.env.today)) {
        const habitId = company.suggestHabitFor(tx.s, out.pet.id);
        if (habitId) company.setCompanion(tx, habitId, out.pet.id);
        else company.noteCompanionOffer(tx);
      }
    });
  }
  if (friends < 14 && s().wallet.stars >= 9 && chance(rng, 0.15)) {
    sim.run((tx) => {
      gacha.pull(tx, 'night');
      gacha.finishReveal(tx);
    });
  }
  if (!s().shelf.places.includes('pond') && s().wallet.coins >= 460 && chance(rng, 0.5)) sim.run((tx) => shelf.buyPlace(tx, 'pond'));
  else if (s().shelf.places.includes('pond') && !s().shelf.places.includes('grass') && s().wallet.coins >= 760 && chance(rng, 0.3)) {
    sim.run((tx) => shelf.buyPlace(tx, 'grass'));
  }
  // Stamps go to Special Order now and then: a wearable or decor that caught the eye, or a treat
  // someone has been hinting at.
  if (s().wallet.stars >= 20 && chance(rng, 0.15)) {
    const orderable = (id: string) => gacha.wishStatus(s(), id, date, gacha.profileCreatedOn(s(), sim.local)).ok;
    const hinted = Object.values(s().pets)
      .filter((p) => !p.favoriteKnown && orderable(p.favoriteTreat))
      .map((p) => p.favoriteTreat);
    const wishes = COLLECTIBLES.filter((c) => (c.category === 'wearable' || c.category === 'decor') && c.rarity !== 'ultra' && orderable(c.id)).map((c) => c.id);
    const pool = hinted.length > 0 && chance(rng, 0.5) ? hinted : wishes;
    if (pool.length > 0) sim.run((tx) => gacha.wish(tx, pick(rng, pool)));
  }
  // Now and then, bake a tray of a favorite recipe.
  const recipes = ownedTreats(s().collection);
  if (recipes.length > 0 && s().wallet.coins >= 150 && chance(rng, 0.05)) sim.run((tx) => pantry.bakeTray(tx, pick(rng, recipes).id));

  const pets = Object.keys(s().pets);
  for (let k = 0; k < 3 && pets.length > 0; k++) {
    const petId = pick(rng, pets);
    sim.run((tx) => {
      for (let t = randomInt(rng, 1, 4); t > 0; t--) friendship.petPet(tx, petId);
    });
    const treats = ownedTreats(s().collection).filter((t) => (s().pantry[t.id]?.servings ?? 0) > 0);
    if (treats.length > 0 && chance(rng, 0.7)) {
      const pet = s().pets[petId]!;
      const favoriteOwned = treats.some((t) => t.id === pet.favoriteTreat);
      const treat = favoriteOwned && chance(rng, 0.35) ? pet.favoriteTreat : pick(rng, treats).id;
      sim.run((tx) => friendship.feedPet(tx, petId, treat));
    }
  }
  // Dress someone up now and then.
  const wearables = ownedWearables(s().collection).filter((w) => w.source !== 'exclusive');
  if (wearables.length > 0 && chance(rng, 0.12)) {
    const w = pick(rng, wearables);
    const petId = pick(rng, pets);
    sim.run((tx) => friendship.setOutfit(tx, petId, w.slot, w.id));
  }
  // Keepsakes go on the sill by their pots.
  for (const k of s().keepsakes ?? []) {
    const itemId = `${company.KEEPSAKE_ITEM_PREFIX}${k.id}`;
    if (shelf.unplacedCopies(s(), itemId) < 1) continue;
    sim.run((tx) => shelf.placeDecor(tx, itemId, 'sill', 0.1 + rng() * 0.8, 0.8, false));
  }
  // Put new decor out.
  for (const [itemId, owned] of Object.entries(s().collection)) {
    if (getCollectible(itemId)?.category !== 'decor' || shelf.unplacedCopies(s(), itemId) < 1 || owned.count < 1) continue;
    const place = s().shelf.places.includes('pond') && chance(rng, 0.3) ? 'pond' : 'sill';
    sim.run((tx) => shelf.placeDecor(tx, itemId, place, 0.1 + rng() * 0.8, 0.35 + rng() * 0.55, chance(rng, 0.3)));
  }
}
