/**
 * Persisted application state. Everything the user owns lives here, is serializable
 * as JSON, and is versioned (see SCHEMA_VERSION + state/migrate.ts).
 * See docs/DESIGN.md §5–§7 for semantics.
 */
import type { MachineId, PastelKey, Personality, PlantSpeciesId, PotId, WearableSlot, DecorSlot } from '@/catalog/types';

export const SCHEMA_VERSION = 1;

/** Local calendar date, 'YYYY-MM-DD'. Never a UTC timestamp. */
export type DateKey = string;
/** 0 = Sunday … 6 = Saturday */
export type Weekday = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type Effort = 'tiny' | 'steady' | 'big';

export type Schedule =
  | { kind: 'daily' }
  | { kind: 'weekdays'; days: Weekday[] }
  | { kind: 'weekly'; times: number }
  | { kind: 'monthly'; times: number };

export interface Pause {
  start: DateKey;
  /** Inclusive. Undefined = still paused. */
  end?: DateKey;
}

export interface Habit {
  id: string;
  name: string;
  emoji: string;
  color: PastelKey;
  plant: PlantSpeciesId;
  pot: PotId;
  schedule: Schedule;
  /** Day-based habits: count needed per scheduled day (1..99). Flexible habits: always 1. */
  target: number;
  unit?: string;
  effort: Effort;
  createdOn: DateKey;
  archivedOn?: DateKey;
  pauses: Pause[];
  order: number;
  /** 'HH:MM' for calendar export. */
  reminder?: string;
  notes?: string;
}

export interface DayLog {
  /** Day-based: progress toward target. Flexible: 0 or 1. */
  count: number;
  /** Intentional rest day (skip). Excluded from consistency, transparent to streaks. */
  rest?: true;
  /** Minutes since local midnight of the most recent check-in (for insights / early-bird badges). */
  t?: number;
}

export interface Wallet {
  coins: number;
  stars: number;
  /** 0..9; every 10 fuses into a star. */
  stardust: number;
  tickets: number;
}

export interface Lifetime {
  coinsEarned: number;
  starsEarned: number;
  checkins: number;
  pulls: number;
  perfectDays: number;
}

export interface Outfit {
  head?: string;
  face?: string;
  neck?: string;
  body?: string;
}
export type OutfitSlot = WearableSlot;

export interface PetState {
  /** Collectible id, e.g. 'pet-cat-calico'. One PetState per owned pet species/variant. */
  id: string;
  name: string;
  personality: Personality;
  favoriteTreat: string;
  favoriteKnown: boolean;
  xp: number;
  outfit: Outfit;
  inMeadow: boolean;
  favorite: boolean;
  obtainedAt: number;
  /** Per-day XP caps; reset when `date` changes. */
  daily: { date: DateKey; pets: number; treats: number; buddy: number };
}

export interface OwnedItem {
  count: number;
  firstAt: number;
}

export interface PityCounter {
  /** Pulls since last rare-or-better. */
  sinceRare: number;
  /** Pulls since last ultra. */
  sinceUltra: number;
  pulls: number;
}

export interface Settings {
  /** 0 = Sunday, 1 = Monday */
  weekStart: 0 | 1;
  theme: 'auto' | 'light' | 'night';
  sound: boolean;
  /** 0..1 */
  volume: number;
  haptics: boolean;
  reduceMotion: 'auto' | 'on' | 'off';
  quickOpen: boolean;
}

export interface Profile {
  name: string;
  /** Pet collectible id shown on Today. */
  buddy: string | null;
  onboarded: boolean;
  createdAt: number;
}

export interface AppState {
  version: number;
  profile: Profile;
  settings: Settings;
  habits: Habit[];
  /** logs[habitId][dateKey] */
  logs: Record<string, Record<DateKey, DayLog>>;
  wallet: Wallet;
  lifetime: Lifetime;
  /**
   * Reward ledger (DESIGN §6.1 "Reward integrity").
   * checkins: key `${habitId}|${dateKey}` → coins granted (0 = recorded as granted but refunded-not-possible).
   *   Absent key = never granted (or refunded), so a (re)check grants.
   * bonuses: any once-only grant key → true. Key formats:
   *   'perfect|<date>' · 'period|<habitId>|<periodKey>' · 'welcome|<habitId>|<date>' ·
   *   'milestone|<habitId>|<rung>' · 'weekly|<weekStartDate>' · 'monthly|<YYYY-MM>' · 'badge|<badgeId>' ·
   *   'plant|<habitId>|<stage>' · 'exclusive|<collectibleId>'
   */
  rewards: {
    checkins: Record<string, number>;
    bonuses: Record<string, true>;
  };
  /** collection[collectibleId] */
  collection: Record<string, OwnedItem>;
  pity: Partial<Record<MachineId, PityCounter>>;
  pets: Record<string, PetState>;
  meadow: {
    decor: Partial<Record<DecorSlot, string>>;
  };
  /** badges[badgeId] = epoch ms when earned */
  badges: Record<string, number>;
  /** Letters (weekly/monthly recaps) waiting to be shown. */
  inbox: Letter[];
  /** True when the save was generated by "Load demo meadow". */
  demo: boolean;
}

export type Letter =
  | {
      kind: 'weekly';
      id: string;
      /** First day of the reported week. */
      weekStart: DateKey;
      achieved: number;
      expected: number;
      stars: number;
      bestHabitId?: string;
    }
  | {
      kind: 'monthly';
      id: string;
      /** 'YYYY-MM' of the reported month. */
      month: string;
      achieved: number;
      expected: number;
      stars: number;
      previousPct?: number;
    };
