/**
 * The committed crescent strings (./data.ts) must match what the generator makes from the shapes.
 * After changing a shape, regenerate with: WRITE_CRESCENTS=1 npx vitest run src/art/scene/crescent
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { buildCrescents, crescentPolygon, flatten, polygonPath, signedArea, type Pt } from './generate';
import { rrect, ellipse } from './build';
import { ALL_CRESCENT_SPECS } from './specs';
import { CRESCENTS } from './data';

const DATA = fileURLToPath(new URL('./data.ts', import.meta.url));

function source(table: ReturnType<typeof buildCrescents>): string {
  const rows = Object.keys(table)
    .sort()
    .map((id) => {
      const t = table[id]!;
      return `  '${id}': {\n    left: '${t.left}',\n    top: '${t.top}',\n    right: '${t.right}',\n  },`;
    });
  return [
    '/**',
    ' * Precomputed shade crescents for the scene\'s own objects, per light position (DESIGN §10.4).',
    ' * GENERATED by ./crescents.test.ts from the shapes in ../props and ../places: do not edit by hand.',
    ' * Regenerate with: WRITE_CRESCENTS=1 npx vitest run src/art/scene/crescent',
    ' */',
    "import type { LightFrom } from '@/art/light';",
    '',
    'export const CRESCENTS: Record<string, Record<LightFrom, string>> = {',
    ...rows,
    '};',
    '',
  ].join('\n');
}

describe('crescent generator', () => {
  const box: Pt[] = [
    [0, 0],
    [10, 0],
    [10, 20],
    [0, 20],
  ];

  it('leaves a sliver on the side away from the light', () => {
    const right = crescentPolygon(box, [-2, 0])!;
    expect(Math.abs(signedArea(right))).toBeCloseTo(2 * 20, 5);
    for (const [x] of right) expect(x).toBeGreaterThanOrEqual(8 - 1e-9);
    const under = crescentPolygon(box, [0, -3])!;
    expect(Math.abs(signedArea(under))).toBeCloseTo(3 * 10, 5);
    for (const [, y] of under) expect(y).toBeGreaterThanOrEqual(17 - 1e-9);
  });

  it('makes an L-shaped sliver for light from above and to one side', () => {
    const c = crescentPolygon(box, [-2, -3])!;
    expect(Math.abs(signedArea(c))).toBeCloseTo(10 * 20 - 8 * 17, 5);
  });

  it('works on curves and in either winding', () => {
    const disc = flatten(ellipse(0, 0, 10, 10), 16);
    const a = crescentPolygon(disc, [-2, 0])!;
    const b = crescentPolygon([...disc].reverse(), [-2, 0])!;
    expect(Math.abs(signedArea(a))).toBeCloseTo(Math.abs(signedArea(b)), 5);
    expect(Math.max(...a.map((p) => p[0]))).toBeCloseTo(10, 1);
    expect(Math.min(...a.map((p) => p[0]))).toBeGreaterThan(-9);
  });

  it('reads the builders\' paths back as closed polygons', () => {
    const p = flatten(rrect(0, 0, 20, 10, 3));
    expect(p.length).toBeGreaterThan(8);
    expect(polygonPath(p)).toMatch(/^M.*Z$/);
  });

  it.each([
    ['Node 22 intersection', 76.84999999999998],
    ['Node 24 intersection', 76.85],
    ['just below the half', 76.85 - 1e-12],
    ['just above the half', 76.85 + 1e-12],
  ])('rounds the same geometric half-tenth consistently: %s', (_label, y) => {
    expect(polygonPath([[0, y], [2, 78], [0, 80]])).toBe('M0 76.9L2 78L0 80Z');
    // Math.round ties toward positive infinity, including negative coordinates.
    expect(polygonPath([[0, -y], [2, -78], [0, -80]])).toBe('M0 -76.8L2 -78L0 -80Z');
  });

  it.each([
    [76.85 - 1e-7, 76.8],
    [76.85 + 1e-7, 76.9],
    [-76.85 - 1e-7, -76.9],
    [-76.85 + 1e-7, -76.8],
  ])('preserves a coordinate genuinely outside the rounding boundary: %s', (y, rounded) => {
    expect(polygonPath([[0, y], [2, 100], [0, 110]])).toBe(`M0 ${rounded}L2 100L0 110Z`);
  });

  it('matches the committed data (regenerate after changing a shape)', () => {
    const table = buildCrescents(ALL_CRESCENT_SPECS);
    if (process.env.WRITE_CRESCENTS) {
      writeFileSync(DATA, source(table));
      return;
    }
    for (const [id, t] of Object.entries(table)) {
      for (const from of ['left', 'top', 'right'] as const) expect(t[from], `${id} ${from}`).not.toBe('');
    }
    expect(CRESCENTS).toEqual(table);
  });
});
