/**
 * Precomputes every Windowlight crescent (DESIGN §10.4) and writes them to data.ts.
 *
 *   npx vite-node src/art/pets/crescents/write.ts
 *
 * Run it after changing any rig shape; the crescent freshness test fails until you do.
 */
import { RIGS } from '../species/rigs';
import { crescentJobs, jobsHash, type Job } from './jobs';
import { clockwise, difference, intersection, multiply, parsePath, rotation, scaling, toPath, transform, translation, type Matrix } from './bezier';

const toMatrix = (at: Job['at']): Matrix =>
  at ? multiply(translation(at[0], at[1]), multiply(rotation(at[3]), scaling(at[2]))) : [1, 0, 0, 1, 0, 0];

export function runJob(job: Job): string {
  const ma = toMatrix(job.at);
  const a = clockwise(transform(parsePath(job.a), ma));
  const mb = multiply(translation(job.shift[0], job.shift[1]), job.b ? toMatrix(job.bAt ?? job.at) : ma);
  const b = clockwise(transform(parsePath(job.b ?? job.a), mb));
  const out = job.op === 'difference' ? difference(a, b) : intersection(a, b);
  if (!job.clip) return toPath(out);
  const c = clockwise(parsePath(job.clip.d));
  return toPath(job.clip.op === 'difference' ? difference(clockwise(out), c) : intersection(clockwise(out), c));
}

/**
 * Runs every job and returns the source of data.ts. Identical jobs share one path string. The
 * data ships as one JSON string (parsed once at load, which is cheaper than a large object
 * literal), with the keys nested by rig and pose so they are not repeated in full.
 */
export function buildData(): { source: string; count: number; bytes: number } {
  const jobs = crescentJobs(RIGS);
  const unique = new Map<string, number>();
  const paths: string[] = [];
  const tree: Record<string, Record<string, Record<string, number>>> = {};
  for (const job of jobs) {
    const { key, ...geometry } = job;
    const sig = JSON.stringify(geometry);
    let i = unique.get(sig);
    if (i === undefined) {
      i = paths.length;
      paths.push(runJob(job));
      unique.set(sig, i);
    }
    if (!paths[i]) continue;
    const [rig, pose, ...rest] = key.split('/');
    ((tree[rig!] ??= {})[pose!] ??= {})[rest.join('/')] = i;
  }
  const bytes = paths.reduce((n, d) => n + d.length, 0);
  // Path data and rig names hold no quotes or backslashes, so the JSON sits in a plain string.
  const json = JSON.stringify({ p: paths, k: tree });
  const source =
    `/* GENERATED by crescents/generate.ts from the rigs. Do not edit; run\n` +
    ` *   npx vite-node src/art/pets/crescents/write.ts\n` +
    ` * after changing a rig. */\n` +
    `export const CRESCENT_HASH = '${jobsHash(jobs)}';\n\n` +
    `/** Path strings (p) and, by rig, then pose (or 'head'), then 'part/kind' or 'kind', their index (k). */\n` +
    `export const DATA: { p: string[]; k: Record<string, Record<string, Record<string, number>>> } = JSON.parse(\n  '${json}',\n);\n`;
  return { source, count: jobs.length, bytes };
}
