/**
 * Precomputes every Windowlight crescent (DESIGN §10.4) and writes them to data.ts.
 *
 *   npx vite-node src/art/pets/crescents/write.ts
 *
 * Run it after changing any rig shape; the crescent freshness test fails until you do.
 */
import { RIGS } from '../species/rigs';
import { crescentJobs, jobsHash, type Job } from './jobs';
import { clockwise, difference, intersection, multiply, parsePath, rotation, scaling, toPath, transform, translation, type Matrix } from './bezier';

const toMatrix = (at: Job['at']): Matrix =>
  at ? multiply(translation(at[0], at[1]), multiply(rotation(at[3]), scaling(at[2]))) : [1, 0, 0, 1, 0, 0];

export function runJob(job: Job): string {
  const ma = toMatrix(job.at);
  const a = clockwise(transform(parsePath(job.a), ma));
  const mb = multiply(translation(job.shift[0], job.shift[1]), job.b ? toMatrix(job.bAt ?? job.at) : ma);
  const b = clockwise(transform(parsePath(job.b ?? job.a), mb));
  return toPath(job.op === 'difference' ? difference(a, b) : intersection(a, b));
}

/** Runs every job and returns the source of data.ts. Identical jobs share one string. */
export function buildData(): { source: string; count: number; bytes: number } {
  const jobs = crescentJobs(RIGS);
  const unique = new Map<string, number>();
  const paths: string[] = [];
  const entries: string[] = [];
  for (const job of jobs) {
    const { key, ...geometry } = job;
    const sig = JSON.stringify(geometry);
    let i = unique.get(sig);
    if (i === undefined) {
      i = paths.length;
      paths.push(runJob(job));
      unique.set(sig, i);
    }
    if (paths[i]) entries.push(`  '${key}': P[${i}]!,`);
  }
  const bytes = paths.reduce((n, d) => n + d.length, 0);
  const source =
    `/* GENERATED by crescents/generate.ts from the rigs. Do not edit; run\n` +
    ` *   npx vite-node src/art/pets/crescents/write.ts\n` +
    ` * after changing a rig. */\n` +
    `export const CRESCENT_HASH = '${jobsHash(jobs)}';\n\n` +
    `const P: readonly string[] = [\n${paths.map((d) => `  '${d}',`).join('\n')}\n];\n\n` +
    `export const CRESCENTS: Readonly<Record<string, string>> = {\n${entries.join('\n')}\n};\n`;
  return { source, count: jobs.length, bytes };
}
